version: '3'
services:
  # db:
  #   image: postgres
  #   restart: always
  #   ports:
  #     - '5432:5432'
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: 1234
  #     POSTGRES_DB: mydb
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: tccapi
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    # links:
    #   - db
    # depends_on:
    #   - db


volumes:
  postgres_data:
